### ISSUE TITLE
Layer navigation gone

### ISSUE THREAD

**Issue by xnhinzkyx** [Sebwite/magento2-category-sidebar#2]
I use the module and it works good but layer navigation is gone. Any idea how to fix this?

Magento 2.0.5

**Comment by waqasraz** [comment]
Same problem here. Unable to get ChidCategories..  any idea?

**Comment by flipflap** [comment]
Same here Magento 2.1.0

**Comment by bacd** [comment]
same problem magento 2.0x

**Comment by mazestricks** [comment]
Hi guys, same here

**Comment by SilvanLaroo** [comment]
Hi all,

The extension overrides the block where the layered navigation should be. See this file: https://github.com/Sebwite/magento2-category-sidebar/blob/master/view/frontend/page_layout/2columns-left.xml. It overrides sidebar.main. You could re-add the layered navigation from your own theme to fix this.
