### ISSUE TITLE
Sidebar category replaces account navigation 

### ISSUE THREAD

**Issue by xnhinzkyx** [Sebwite/magento2-category-sidebar#3]
I manage to make it work but it shows every pages in the left sidebar, and it replaces the account navigation.. any fixes for this?

Thanks.

**Comment by JensBourgeois** [comment]
Hello,

I have the same problem, after installing the module, I get a blank page when trying to go to 
"http://www.shop.dev/customer/account/"

**Comment by mazestricks** [comment]
Hi, 

I have the same problem with this module. after I installed into the site. The account navigation was replaced just like xnhinzkyx experienced. any fix for this guys? 

Thanks,
![sebwite bug](https://cloud.githubusercontent.com/assets/14094984/22055764/b96ce668-dd97-11e6-91fa-0b238cd31bec.jpg)

**Comment by mazestricks** [comment]
Hi Guys,

I manage to fix the account dashboard problem.

I created a solution in here: http://magento.stackexchange.com/questions/155220/magento-2-account-dashboard-was-messed-up-after-installing-magento2-category-sid/155393#155393

Just follow that and you will regain your account dashboard back. It seems that this container name "div.sidebar.main" in the layout of sidebar.phtml in sebwite will overwrite the account dashboard


Now here's the look of my account dashboard:

![7r2cg](https://cloud.githubusercontent.com/assets/14094984/22093217/dcb0b238-de3e-11e6-98ae-c4f252690d65.png)


Thanks, I hope this will help you guys.

**Comment by SilvanLaroo** [comment]
I've released a new version that will not override the sidebar but just add the category block to it. This will fix your issue as well.
